/* EDUQUEST — Laboratorio de Derivadas. No usa eval(); math.js interpreta expresiones. */
const state={funcs:[{f:'sin(x)',d:'cos(x)'},{f:'x^2-4',d:'2*x'},{f:'exp(0.3*x)',d:'0.3*exp(0.3*x)'}],cover:'',ar:false,stream:null};
const $=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)];
function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),3000)}
function fmt(x,d=5){return Number.isFinite(x)?Number(x.toFixed(d)).toString():'—'}
function nums(s){return s.split(/[\s,;]+/).map(Number).filter(Number.isFinite)}
function rng(a,b,n){const r=[],h=(b-a)/(n-1);for(let i=0;i<n;i++)r.push(a+i*h);return r}
function allowed(expr,vars=['x']){if(!expr||expr.length>150||/[;{}\[\]=]|eval|import|require|load\(/i.test(expr))return false;try{const sy=math.parse(expr).filter(n=>n.isSymbolNode).map(n=>n.name);return sy.every(s=>vars.includes(s)||['sin','cos','tan','asin','acos','atan','sqrt','abs','exp','log','ln','pi','e','pow'].includes(s))}catch{return false}}
function ev(expr,scope){try{return Number(math.parse(expr).evaluate(scope))}catch{return NaN}}
function derivativeNumeric(expr,x,h=1e-5){return(ev(expr,{x:x+h})-ev(expr,{x:x-h}))/(2*h)}
function roots(expr,a,b){const xs=rng(a,b,700),out=[];let px=xs[0],pf=ev(expr,{x:px});for(let i=1;i<xs.length;i++){const x=xs[i],f=ev(expr,{x});if(Number.isFinite(f)&&Number.isFinite(pf)&&pf*f<0){let l=px,r=x,fl=pf;for(let k=0;k<55;k++){let m=(l+r)/2,fm=ev(expr,{x:m});if(fl*fm<=0)r=m;else{l=m;fl=fm}}let z=(l+r)/2;if(!out.length||Math.abs(z-out.at(-1))>.001)out.push(z)}px=x;pf=f}return out}
function nav(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('pageTitle').textContent={home:'Inicio / ingreso',concept:'Conceptos y reglas',explain:'Explicación',exercises:'Ejercicios',geometry:'Representación geométrica',xr:'Laboratorio XR',teacher:'Modo docente',assessment:'Ingreso y valoración'}[v];$('sidebar').classList.remove('open');if(v==='geometry')plotGeometry();if(v==='xr')initAFrame()}
function plotFunctions(){const fs=[1,2,3].map(i=>({f:$('f'+i).value.trim(),d:$('d'+i).value.trim()}));if(fs.some(q=>!allowed(q.f)||!allowed(q.d))){toast('Revisa las expresiones: solo se permiten operaciones y funciones matemáticas seguras.');return}state.funcs=fs;const a=+$('xmin').value,b=+$('xmax').value,n=Math.min(2000,Math.max(50,+$('samples').value||400)),x0=+$('x0').value,x=rng(a,b,n),tr=[];fs.forEach((q,i)=>{const y=x.map(z=>ev(q.f,{x:z})),d=x.map(z=>ev(q.d,{x:z}));tr.push({x,y,mode:'lines',name:'f'+(i+1)+'(x) = '+q.f});tr.push({x,y:d,mode:'lines',name:'f'+(i+1)+'′(x) = '+q.d,line:{dash:'dot'}})});const checks=fs.map(q=>{try{return math.simplify(math.derivative(q.f,'x')).equals(math.simplify(q.d))}catch{return false}});const y0=ev(fs[0].f,{x:x0}),s=ev(fs[0].d,{x:x0});tr.push({x,y:x.map(z=>y0+s*(z-x0)),mode:'lines',name:'Tangente',line:{dash:'dash',color:'#111'}});Plotly.newPlot('functionPlot',tr,{paper_bgcolor:'transparent',plot_bgcolor:'transparent',xaxis:{title:'x'},yaxis:{title:'y'},margin:{l:50,r:20,t:25,b:45},legend:{orientation:'h'}},{responsive:true,displaylogo:false});const rr=roots(fs[0].f,a,b);$('functionInfo').innerHTML=`<div class="metrics"><div class="metric">f₁(x₀)<b>${fmt(y0)}</b></div><div class="metric">f₁′(x₀)<b>${fmt(s)}</b></div><div class="metric">Raíces aprox.<b>${rr.length?rr.map(z=>fmt(z,3)).join(', '):'No detectadas'}</b></div><div class="metric">Comprobación simbólica<b>${checks.map((v,i)=>'f'+(i+1)+': '+(v?'✓':'Revisar')).join(' · ')}</b></div></div>`;const rows=x.slice(0,12).map(z=>`<tr><td>${fmt(z)}</td><td>${fmt(ev(fs[0].f,{x:z}))}</td><td>${fmt(ev(fs[0].d,{x:z}))}</td></tr>`).join('');$('functionRows').innerHTML=rows}
function csv(){const x=rng(+$('xmin').value,+$('xmax').value,Math.min(2000,+$('samples').value||400));const rows=[['x','f1','f1_derivada','f2','f2_derivada','f3','f3_derivada']];x.forEach(z=>rows.push([z,...state.funcs.flatMap(q=>[ev(q.f,{x:z}),ev(q.d,{x:z})])]));const b=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='eduquest-funciones.csv';a.click()}
function png(id,name){Plotly.downloadImage(id,{format:'png',filename:name,width:1400,height:850})}
const rules=[['Constante','f(x)=c','f′(x)=0'],['Identidad','f(x)=x','f′(x)=1'],['Lineal','f(x)=mx+b','f′(x)=m'],['Potencia','f(x)=xⁿ','f′(x)=n·xⁿ⁻¹'],['Cuadrática','f(x)=ax²+bx+c','f′(x)=2ax+b'],['Exponencial','f(x)=eˣ','f′(x)=eˣ'],['Base a','f(x)=aˣ','f′(x)=aˣ ln(a)'],['Seno','sin(x)','cos(x)'],['Coseno','cos(x)','−sin(x)'],['Producto','uv','u′v+uv′'],['Cociente','u/v','(u′v−uv′)/v²'],['Cadena','g(h(x))','g′(h(x))h′(x)'],['Máximo/mínimo','f′(x)=0','Puntos críticos'],['Aplicaciones','cambio y optimización','Interpretación de tasas']];
function renderRules(){$('rules').innerHTML=rules.map(r=>`<article class="card rule"><h3>${r[0]}</h3><p class="formula">${r[1]} → ${r[2]}</p><p class="muted">Identifica la estructura antes de aplicar la regla y simplifica al final.</p></article>`).join('')}
const ex=[['Deriva x³−4x+2','3*x^2-4'],['Deriva sin(x)+x²','cos(x)+2*x'],['Deriva exp(0.3*x)','0.3*exp(0.3*x)'],['Deriva (x²+1)(x−3)','2*x*(x-3)+(x^2+1)'],['Deriva (x²+1)/(x−1)','(2*x*(x-1)-(x^2+1))/(x-1)^2'],['Si f=x²−4, calcula f′(2)','4']];
function renderEx(){ $('exList').innerHTML=ex.map((q,i)=>`<article class="exercise"><b>${i+1}. ${q[0]}</b><div class="field"><label>Respuesta</label><input id="ex${i}"></div><div class="actions"><button class="btn" onclick="checkEx(${i})">Comprobar</button><span id="fb${i}"></span></div></article>`).join('')}
function checkEx(i){let ok=false;try{ok=math.simplify($('ex'+i).value).equals(math.simplify(ex[i][1]))}catch{}const f=$('fb'+i);f.className='feedback '+(ok?'ok':'bad');f.textContent=ok?'✓ Correcto':'Revisa la regla y vuelve a intentarlo.'}
function plotGeometry(){const x=rng(-6,6,250),f=state.funcs[0]?.f||'sin(x)';Plotly.newPlot('geometryPlot',[{x,y:x.map(z=>ev(f,{x:z})),name:'f(x)',mode:'lines'},{x,y:x.map(z=>derivativeNumeric(f,z)),name:'f′(x) numérica',mode:'lines'}],{paper_bgcolor:'transparent',plot_bgcolor:'transparent',xaxis:{title:'x'},yaxis:{title:'y'},margin:{l:50,r:20,t:25,b:45}},{responsive:true,displaylogo:false})}
function surface(){const e=$('surfExpr').value.trim(),n=Math.min(80,Math.max(15,+$('surfRes').value||40));if(!allowed(e,['x','y'])){toast('Superficie no válida. Usa x, y y funciones matemáticas permitidas.');return}const xs=rng(-4,4,n),ys=rng(-4,4,n),z=ys.map(y=>xs.map(x=>ev(e,{x,y}))),x0=+$('sx0').value,y0=+$('sy0').value,h=1e-4,z0=ev(e,{x:x0,y:y0}),zx=(ev(e,{x:x0+h,y:y0})-ev(e,{x:x0-h,y:y0}))/(2*h),zy=(ev(e,{x:x0,y:y0+h})-ev(e,{x:x0,y:y0-h}))/(2*h);Plotly.newPlot('surfacePlot',[{type:'surface',x:xs,y:ys,z,colorscale:[[0,'#0877c9'],[.5,'#00C2FF'],[.75,'#B8EF2B'],[1,'#FF7A1A']],contours:{z:{show:true,project:{z:true}}}}],{paper_bgcolor:'transparent',scene:{xaxis:{title:'x'},yaxis:{title:'y'},zaxis:{title:'z'}},margin:{l:0,r:0,t:20,b:0}},{responsive:true,displaylogo:false});$('surfaceInfo').innerHTML=`<div class="metrics"><div class="metric">z(x₀,y₀)<b>${fmt(z0)}</b></div><div class="metric">∂z/∂x<b>${fmt(zx)}</b></div><div class="metric">∂z/∂y<b>${fmt(zy)}</b></div><div class="metric">|∇z|<b>${fmt(Math.hypot(zx,zy))}</b></div></div>`}
function stats(){const d=nums($('data').value);if(!d.length)return toast('Introduce datos numéricos.');d.sort((a,b)=>a-b);const n=d.length,m=d.reduce((a,b)=>a+b,0)/n,med=n%2?d[(n-1)/2]:(d[n/2-1]+d[n/2])/2,q=p=>{const k=(n-1)*p,l=Math.floor(k),h=Math.ceil(k);return d[l]+(d[h]-d[l])*(k-l)},q1=q(.25),q3=q(.75),vp=d.reduce((s,x)=>s+(x-m)**2,0)/n,vs=n>1?vp*n/(n-1):NaN,c={};d.forEach(x=>c[x]=(c[x]||0)+1);const mc=Math.max(...Object.values(c)),mode=mc>1?Object.keys(c).filter(k=>c[k]===mc).join(', '):'Sin moda';$('stats').innerHTML=Object.entries({n,media:m,mediana:med,moda:mode,min:d[0],max:d.at(-1),rango:d.at(-1)-d[0],Q1:q1,Q3:q3,IQR:q3-q1,varianzaP:vp,varianzaM:vs,desvP:Math.sqrt(vp),desvM:Math.sqrt(vs)}).map(([k,v])=>`<div class="metric">${k}<b>${typeof v==='string'?v:fmt(v,4)}</b></div>`).join('');Plotly.newPlot('hist',[{x:d,type:'histogram'}],{paper_bgcolor:'transparent',plot_bgcolor:'transparent',margin:{l:40,r:15,t:15,b:40}},{responsive:true,displaylogo:false});Plotly.newPlot('box',[{y:d,type:'box',boxpoints:'outliers'}],{paper_bgcolor:'transparent',plot_bgcolor:'transparent',margin:{l:40,r:15,t:15,b:40}},{responsive:true,displaylogo:false})}
function regression(){const x=nums($('xdata').value),y=nums($('ydata').value);if(x.length<2||x.length!==y.length)return toast('X e Y deben tener la misma cantidad de datos.');const n=x.length,mx=x.reduce((a,b)=>a+b)/n,my=y.reduce((a,b)=>a+b)/n;let num=0,den=0;for(let i=0;i<n;i++){num+=(x[i]-mx)*(y[i]-my);den+=(x[i]-mx)**2}const b=num/den,a=my-b*mx,r=num/Math.sqrt(den*y.reduce((s,v)=>s+(v-my)**2,0));$('reg').innerHTML=`<div class="metrics"><div class="metric">r<b>${fmt(r,4)}</b></div><div class="metric">Pendiente b<b>${fmt(b,4)}</b></div><div class="metric">Intercepto a<b>${fmt(a,4)}</b></div><div class="metric">R²<b>${fmt(r*r,4)}</b></div></div><p class="formula">ŷ = ${fmt(a,4)} + (${fmt(b,4)})x</p><p class="muted">Correlación no implica causalidad.</p>`;const xx=[Math.min(...x),Math.max(...x)];Plotly.newPlot('regPlot',[{x,y,mode:'markers',name:'Datos'},{x:xx,y:xx.map(z=>a+b*z),mode:'lines',name:'Regresión'}],{paper_bgcolor:'transparent',plot_bgcolor:'transparent',margin:{l:45,r:15,t:15,b:45}},{responsive:true,displaylogo:false})}
function solid(){const type=$('solid').value,r=+$('r').value,h=+$('h').value,w=+$('w').value,d=+$('d').value,t=+$('t').value;let v=0,a=0,formula='';if(type==='sphere'){v=4*Math.PI*r**3/3;a=4*Math.PI*r**2;formula='V=4πr³/3; A=4πr²'}if(type==='cylinder'){v=Math.PI*r*r*h;a=2*Math.PI*r*(r+h);formula='V=πr²h; A=2πr(r+h)'}if(type==='cone'){v=Math.PI*r*r*h/3;a=Math.PI*r*(r+Math.hypot(r,h));formula='V=πr²h/3; A=πr(r+√(r²+h²))'}if(type==='box'){v=w*h*d;a=2*(w*h+w*d+h*d);formula='V=whd; A=2(wh+wd+hd)'}if(type==='torus'){v=2*Math.PI**2*r*t*t;a=4*Math.PI**2*r*t;formula='V=2π²Rt²; A=4π²Rt'}$('solidInfo').innerHTML=`<div class="metrics"><div class="metric">Volumen<b>${fmt(v,3)}</b></div><div class="metric">Área<b>${fmt(a,3)}</b></div><div class="metric">Fórmula<b>${formula}</b></div><div class="metric">Conjetura<b>¿Cómo cambia V si duplicas las longitudes?</b></div></div>`;buildSolid(type)}
function initAFrame(){if(window.AFRAME)return;const s=document.createElement('script');s.src='https://aframe.io/releases/1.6.0/aframe.min.js';s.onload=()=>{toast('A-Frame listo');buildSolid('sphere')};document.head.appendChild(s)}
function buildSolid(type){const scene=$('scene');if(!scene||!window.AFRAME)return;let ent='';if(type==='sphere')ent='<a-sphere radius="1.3" color="#00C2FF" opacity=".82"></a-sphere>';if(type==='cylinder')ent='<a-cylinder radius="1.1" height="2.5" color="#00C2FF" opacity=".82"></a-cylinder>';if(type==='cone')ent='<a-cone radius-bottom="1.25" radius-top="0" height="2.5" color="#00C2FF" opacity=".82"></a-cone>';if(type==='box')ent='<a-box width="2.5" height="1.8" depth="1.6" color="#00C2FF" opacity=".82"></a-box>';if(type==='torus')ent='<a-torus radius="1.3" radius-tubular=".35" color="#00C2FF" opacity=".82"></a-torus>';scene.innerHTML=`<a-entity id="solidObj" position="0 1.2 -4">${ent}<a-entity rotation="0 0 0" geometry="primitive: box; width:2.7; height:2.7; depth:2.7" material="color:#B8EF2B;wireframe:true;opacity:.22"></a-entity></a-entity><a-entity light="type:ambient;intensity:1"></a-entity><a-entity light="type:directional;intensity:.8" position="2 4 4"></a-entity><a-camera position="0 2 7"></a-camera>`}
function startAR(){const secure=location.protocol==='https:'||location.hostname==='localhost';const cam=!!navigator.mediaDevices?.getUserMedia;$('arDiag').innerHTML=`<div class="metrics"><div class="metric">HTTPS<b>${secure?'Sí':'No'}</b></div><div class="metric">Cámara API<b>${cam?'Disponible':'No disponible'}</b></div><div class="metric">Ventana<b>${top===self?'Pestaña':'Incrustada'}</b></div></div>`;if(!secure||!cam)return toast('La RA necesita HTTPS y una cámara disponible. Continúa con 3D/RV.');if(state.ar)return;const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/ar.js@3.4.5/aframe/build/aframe-ar.js';s.onload=()=>{state.ar=true;$('arHost').innerHTML='<div class="arStatus" id="arState">Buscando marcador Hiro…</div><a-scene embedded vr-mode-ui="enabled:false" renderer="logarithmicDepthBuffer:true" arjs="sourceType:webcam;debugUIEnabled:false"><a-marker preset="hiro" smooth="true" smoothCount="5" smoothTolerance="0.01" smoothThreshold="5" id="hiro"><a-box position="0 .5 0" color="#00C2FF" opacity=".8"></a-box><a-text value="Eduquest" align="center" color="#B8EF2B" position="0 1.3 0"></a-text></a-marker><a-entity camera></a-entity></a-scene>';const m=$('hiro');m?.addEventListener('markerFound',()=>{$('arState').textContent='Marcador detectado ✓'});m?.addEventListener('markerLost',()=>{$('arState').textContent='Buscando marcador Hiro…'});toast('RA activada. Apunta al marcador Hiro.')};s.onerror=()=>toast('No fue posible cargar AR.js. El modo 3D sigue disponible.');document.head.appendChild(s)}
function closeAR(){document.querySelectorAll('#arHost video').forEach(v=>v.srcObject?.getTracks().forEach(t=>t.stop()));$('arHost').innerHTML='<div style="height:420px;display:grid;place-items:center;color:#9eb2c6">RA cerrada. 3D/RV disponibles.</div>';state.ar=false}
function projectSave(){const p={title:$('ptitle').value,level:$('plevel').value,duration:$('pduration').value,objective:$('pobjective').value,challenge:$('pchallenge').value,evidence:$('pevidence').value};localStorage.setItem('eduquestProject',JSON.stringify(p));renderProject(p);toast('Proyecto guardado en localStorage.')}
function renderProject(p){$('script').textContent=`1. OBSERVAR: ${p.title}\n2. CALCULAR: aplicar la regla adecuada.\n3. EXPLICAR: justificar el procedimiento y comprobarlo gráficamente.\n4. TRANSFERIR: resolver una situación nueva.\n\nNivel: ${p.level}\nDuración: ${p.duration}\nObjetivo: ${p.objective}\nPregunta retadora: ${p.challenge}\nEvidencia: ${p.evidence}`}
function exportProject(){const p=JSON.parse(localStorage.getItem('eduquestProject')||'null');if(!p)return toast('Guarda primero el proyecto.');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));a.download='eduquest-proyecto.json';a.click()}
function importProject(file){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);[['ptitle','title'],['plevel','level'],['pduration','duration'],['pobjective','objective'],['pchallenge','challenge'],['pevidence','evidence']].forEach(([a,b])=>$(a).value=p[b]||'');renderProject(p);toast('Proyecto importado.')}catch{toast('JSON inválido.')}};r.readAsText(file)}
function assess(){const n=$('student').value.trim(),s=Math.max(0,Math.min(100,+$('score').value));if(!n)return toast('Escribe el nombre del estudiante.');localStorage.setItem('eduquest_'+n,JSON.stringify({name:n,score:s,note:$('note').value,date:new Date().toISOString()}));$('assessmentOut').innerHTML=`<div class="metric"><span>Valoración</span><b>${s}/100</b></div><p>Registro local guardado para ${n}.</p>`}
function speak(){const txt=document.querySelector('.view.active')?.innerText||'Eduquest Laboratorio de Derivadas';if(!('speechSynthesis'in window))return toast('Narración no disponible.');speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(txt.slice(0,3500)))}
function init(){const cover=$('coverImage');cover.src='data:image/png;base64,'+window.EDUQUEST_COVER;$('homeCover').src=cover.src;$('start').onclick=()=>{$('coverScreen').classList.add('hide');nav('home')};$('openCover').onclick=()=>{$('coverScreen').classList.remove('hide')};$('closeCover').onclick=()=>{$('coverScreen').classList.add('hide')};$('menu').onclick=()=>$('sidebar').classList.toggle('open');$$('.nav button').forEach(b=>b.onclick=()=>nav(b.dataset.view));$('contrast').onclick=()=>document.body.classList.toggle('high');$('narrate').onclick=speak;$('plot').onclick=plotFunctions;$('csv').onclick=csv;$('functionPNG').onclick=()=>png('functionPlot','eduquest-derivadas');$('solid').onchange=solid;['r','h','w','d','t'].forEach(id=>$(id).oninput=solid);$('rotate').onclick=()=>{const e=$('solidObj');e?.setAttribute('animation','property:rotation;to:0 360 0;dur:10000;loop:true;easing:linear')};$('pause').onclick=()=>{$('solidObj')?.removeAttribute('animation')};$('reset').onclick=()=>buildSolid($('solid').value);$('surfaceBtn').onclick=surface;$('arStart').onclick=startAR;$('arClose').onclick=closeAR;$('statsBtn').onclick=stats;$('regBtn').onclick=regression;$('save').onclick=projectSave;$('export').onclick=exportProject;$('import').onchange=e=>e.target.files[0]&&importProject(e.target.files[0]);$('assess').onclick=assess;renderRules();renderEx();const p=JSON.parse(localStorage.getItem('eduquestProject')||'null');if(p){[['ptitle','title'],['plevel','level'],['pduration','duration'],['pobjective','objective'],['pchallenge','challenge'],['pevidence','evidence']].forEach(([a,b])=>$(a).value=p[b]||'');renderProject(p)}setTimeout(()=>{initAFrame();plotFunctions();plotGeometry()},300);$('engine').innerHTML='<span class="dot"></span>math.js: listo · Plotly: listo';$('webxr').textContent='WebXR: '+(navigator.xr?'disponible':'no expuesto por este navegador')}
document.addEventListener('DOMContentLoaded',init);
